---
abstract: 'Encode::JP::Mobile friendly'
author:
  - 'Tokuhiro Matsuno <tokuhirom aaaatttt gmail dotottto commmmm>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-MobileAgent-Plugin-Charset
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::MobileAgent: 0.26
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
